#!/usr/bin/env python

# DO NOT EDIT THIS FILE : Generated from scribe/notebooks/wakeword.ipynb

from  mangorest.mango import webapi
import colabexts.utils as colabexts_utils
import logging, os, datetime
logger = logging.getLogger( "geoapp" )

# ------------------------------------------------------------------------------
@webapi("/asthma/update/")
def updateRecord(request=None, **kwargs): 
    user_id = kwargs.get('user_id', '')
    cur_time = kwargs.get('cur_time', '')  
    logger.info( f"+++++++++++ {user_id} {cur_time}" )
    if not user_id:
        return "no userid!!"

    return f"updated !!"

if __name__ == '__main__' and not colabexts_utils.inJupyter():
    updateRecord(None, None)
